name: Deploy to Production

on:
  push:
    branches:
      - main  # Cambia esto si deseas desplegar desde otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Copy dist folder to production repository
        run: |
          mkdir -p ../production-repo/dist
          cp -r dist/* ../production-repo/dist/

      - name: Commit and push changes to production repository
        run: |
          cd ../production-repo
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Deploy latest dist files"
          git push origin main  # Cambia esto si el repositorio de destino usa otra rama
